name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Hub auth
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Docker image construction
        uses: docker/build-push-action@v5.2.0 
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            rafaspimenta/kube-news:v1
            rafaspimenta/kube-news:latest          
